FROM openjdk:11
EXPOSE 6061
WORKDIR /usr/app/springboot-database-profiles
ADD target/springboot-database-profiles-0.0.1.jar springboot-database-profiles-0.0.1.jar
ENTRYPOINT ["java", "-jar", "springboot-database-profiles-0.0.1.jar"]